### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by tristan-k** [edouard-lopez/sshuttle-helper#1]
I'm using Ubuntu 14.04 with the latest sshuttle. 

```
Starting proxy-ssh...
Traceback (most recent call last):
  File "/usr/lib/sshuttle/main.py", line 123, in <module>
    opt.syslog, opt.daemon, opt.pidfile))
  File "/usr/lib/sshuttle/client.py", line 391, in main
    seed_hosts, auto_nets, syslog, daemon)
  File "/usr/lib/sshuttle/client.py", line 250, in _main
    options=dict(latency_control=latency_control))
  File "/usr/lib/sshuttle/ssh.py", line 46, in connect
    portl = ['-p', str(int(l[1]))]
ValueError: invalid literal for int() with base 10: 'hostserver-address'
```

**Comment by edouard-lopez** [comment]
This look like a sshuttle error, what command did you run?
